obj-$(CONFIG_SB_CORE)	+= sb-core.o
sb-core-$(CONFIG_SB_CORE)	+= sb_core.o
sb-core-$(CONFIG_SB_PQUEUE)	+= sb_pqueue.o
sb-core-$(CONFIG_SB_NOTIFY)	+= sb_notify.o
sb-core-$(CONFIG_SB_SYSFS)	+= sb_sysfs.o
sb-core-$(CONFIG_SB_VOTE)	+= sb_vote.o

ccflags-y := -Wformat
