obj-$(CONFIG_SB_MFC)		+= sb-mfc.o
sb-mfc-$(CONFIG_SB_MFC)		+= sb_mfc.o

obj-$(CONFIG_WIRELESS_CHARGER_CPS4038)	+= cps4038_charger.o

ccflags-y := -Wformat

obj-$(CONFIG_WIRELESS_CHARGER_S2MIW04)	+= s2miw04_charger.o

ccflags-y := -Wformat

obj-$(CONFIG_WIRELESS_CHARGER_P9320)	+= p9320_charger.o

ccflags-y := -Wformat
